const schema = require("../schema")
const schemaName = schema.name
const mainTable = schema.table.reserv
const refTable = schema.table.user
const refColumn = schema.column.reserv_ref_user

exports.up = function (knex, Promise) {
    return Promise.all([
        
        // ** For timestamp yyyy-mm-dd hh-mm-ss เลือกข้ามวัน
        knex.schema.createTable(`${schemaName}.${mainTable}`, function (table) {
            table.integer('id').unique().notNull();
            table.integer(`facility_id`)
                .notNull()
                .references('id')
                .inTable(`meeteenew.facility`)
                .onDelete('CASCADE');
            table.timestamp('start_time').notNull();
            table.timestamp('end_time').notNull();
            table.string('status').notNull();
            table.integer(`${refColumn}`)
                .unsigned()
                .notNull()
                .references('id')
                .inTable(`${schemaName}.${refTable}`)
                .onDelete('CASCADE');
            table.timestamp('created_at').defaultTo(knex.fn.now());
        })
        .raw(`ALTER TABLE ${schemaName}.${mainTable} ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 10001)`)
        .raw(`ALTER TABLE ${schemaName}.${mainTable} ADD CHECK (start_time >= current_timestamp AND end_time >= current_timestamp)`)
        .raw(`ALTER TABLE ${schemaName}.${mainTable} ADD CHECK (status IN ('Booked', 'Cancelled'))`)

        // ** For time and date ของได้ในวันเดียวเท่านั้น ร้านไม่เปิดข้ามวัน
        // knex.schema.createTable(`${schemaName}.${mainTable}`, function (table) {
        //     table.integer('id').unique().notNull();
        //     table.integer(`facility_id`)
        //         .notNull()
        //         .references('id')
        //         .inTable(`meeteenew.facility`)
        //         .onDelete('CASCADE');
        //     table.date('in_date').notNull();
        //     table.time('start_time').notNull();
        //     table.time('end_time').notNull();
        //     table.string('status').notNull();
        //     table.integer(`${refColumn}`)
        //         .unsigned()
        //         .notNull()
        //         .references('id')
        //         .inTable(`${schemaName}.${refTable}`)
        //         .onDelete('CASCADE');
        //     table.timestamp('created_at').defaultTo(knex.fn.now());
        // })
        // .raw(`ALTER TABLE ${schemaName}.${mainTable} ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 10001)`)
        // .raw(`ALTER TABLE ${schemaName}.${mainTable} ADD CHECK ((SELECT in_date + ' ' + start_time) >= current_timestamp AND (SELECT in_date + ' ' + end_time) >= current_timestamp)`)
        // .raw(`ALTER TABLE ${schemaName}.${mainTable} ADD CHECK (status IN ('Booked', 'Cancelled'))`)

        // ** For fac-multiple-choosing
        // knex.schema.createTable(`${schemaName}.${mainTable}`, function (table) {
        //     table.integer('id').unique().notNull();
        //     table.timestamp('start_time').notNull();
        //     table.timestamp('end_time').notNull();
        //     table.string('status').notNull();
        //     table.integer(`${refColumn}`)
        //         .unsigned()
        //         .notNull()
        //         .references('id')
        //         .inTable(`${schemaName}.${refTable}`)
        //         .onDelete('CASCADE');
        //     table.timestamp('created_at').defaultTo(knex.fn.now());
        // })
        // // .raw(`ALTER TABLE ${schemaName}.${mainTable} ALTER COLUMN id DROP DEFAULT`)
        // .raw(`ALTER TABLE ${schemaName}.${mainTable} ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 10001)`)
        // // .raw(`ALTER TABLE ${schemaName}.${mainTable} ADD CHECK (start_date >= current_date AND end_date >= current_date)`)
        // .raw(`ALTER TABLE ${schemaName}.${mainTable} ADD CHECK (start_time >= current_timestamp AND end_time >= current_timestamp)`)
        // .raw(`ALTER TABLE ${schemaName}.${mainTable} ADD CHECK (status IN ('Booked', 'Cancelled'))`)
        // // .raw(`ALTER TABLE ${schemaName}.${mainTable} ALTER COLUMN id AUTO_INCREMENT = 10001`)
        // // .raw(`ALTER TABLE ${schemaName}.${mainTable} SEQUENCE reservation_id_seq START WITH 10001`)
        // // .raw(`ALTER COLUMN id SET (START WITH 10001 INCREMENT BY 1)`)
    ]);
};

exports.down = function (knex, Promise) {
    return knex.schema.dropTable(`${schemaName}.${mainTable}`)
};