const schema = require("../schema")
const schemaName = schema.name
const mainTable = schema.table.reserv
const refTable = schema.table.user
const refColumn = schema.column.reserv_ref_user

exports.up = function (knex, Promise) {
    return Promise.all([
        knex.schema.createTable(`${schemaName}.${mainTable}`, function (table) {
            table.integer('id').unique().notNull();
            // table.increments('id').primary();
            // knex.schema.raw(`ALTER TABLE ${schemaName}.${mainTable} ALTER COLUMN id DROP DEFAULT`)
            // knex.schema.raw(`ALTER TABLE ${schemaName}.${mainTable} ALTER COLUMN id DROP CONSTRAINT`)
            // knex.schema.raw(`ALTER TABLE ${schemaName}.${mainTable} ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 10001 INCREMENT BY 1)`)
            // table.date('start_date').notNull();
            // table.time('start_time').notNull();
            // table.date('end_date').notNull();F
            // table.time('end_time').notNull();
            table.timestamp('start_time').notNull();
            table.timestamp('end_time').notNull();
            table.string('status').notNull();
            table.integer(`${refColumn}`)
                .unsigned()
                .notNull()
                .references('id')
                .inTable(`${schemaName}.${refTable}`)
                .onDelete('CASCADE');
            table.timestamp('created_at').defaultTo(knex.fn.now());
        })
        // .raw(`ALTER TABLE ${schemaName}.${mainTable} ALTER COLUMN id DROP DEFAULT`)
        .raw(`ALTER TABLE ${schemaName}.${mainTable} ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 10001)`)
        // .raw(`ALTER TABLE ${schemaName}.${mainTable} ADD CHECK (start_date >= current_date AND end_date >= current_date)`)
        .raw(`ALTER TABLE ${schemaName}.${mainTable} ADD CHECK (start_time >= current_timestamp AND end_time >= current_timestamp)`)
        .raw(`ALTER TABLE ${schemaName}.${mainTable} ADD CHECK (status IN ('Booked', 'Cancelled'))`)
        // .raw(`ALTER TABLE ${schemaName}.${mainTable} ALTER COLUMN id AUTO_INCREMENT = 10001`)
        // .raw(`ALTER TABLE ${schemaName}.${mainTable} SEQUENCE reservation_id_seq START WITH 10001`)
        // .raw(`ALTER COLUMN id SET (START WITH 10001 INCREMENT BY 1)`)
    ]);
};

exports.down = function (knex, Promise) {
    return knex.schema.dropTable(`${schemaName}.${mainTable}`)
};